### ISSUE TITLE
Master vs Dev

### ISSUE THREAD

**Issue by kamronbatman** [jundis/CWSlack-SlashCommands#100] opened 2017-02-08 20:32 UTC
It looks like updating to latest is pulling from master, which is a work in progress.  There is even a comment stating that the code is a development build.

I suggest master stays at a stable release build, and a formal develop branch is created for work in progress code.  This will prevent upgrade issues, and confusion between releases, stable code, and what is currently being developed.

Also FYI, I bring this up cause master is currently broken.  It throws the following errors:
"Array is not returned on line 195."
and
"array_key_exists() expects parameter 2 to be array, null is given" - This was for functions.php on line 58

After downgrading to v2.3, everything works - No configuration changes required.

**Comment by jundis** [comment] 2017-02-09 14:23
I'll look into doing that in the future.

As for that error you got, I just rebuilt my live environment of this script using the latest files from GitHub and there were no issues.

The error you received is typically caused by an issue with your $connectwise variable being incorrect, though can be any part of the CW connection, as that error will only appear if it cannot get a valid json return from ConnectWise and just gets http errors.

Should you come across it again, please use the latest functions.php and add $debugmode = true; to anywhere in your config.php file.

**Comment by kamronbatman** [comment] 2017-02-09 20:45
Ok I will try that. Keep in mind, with the same config.php file changes, the v2.3 release works perfectly.  So I assume its a change in the code between v2.3 release and master.

**Comment by jundis** [comment] 2017-02-10 00:30
The only thing that changed that could affect that is the addition of the $connectwisebranch variable replacing v4_6_release in all URLs in the code.

If you could try that again when you have time and download the latest files and set $debugmode = true; at the bottom of config.php, that would help in determining whats going wrong.

**Comment by jundis** [comment] 2017-02-17 21:08
Will move ongoing development to developer branch after 2.4 changes are pushed as release.

**Comment by jundis** [comment] 2017-09-18 14:46
v3.0 will be the next release as a full redesign, only bug fixes and internally requested features added until then. Closing, will create separate branch for v3

**Closed as completed by jundis** 2017-09-18 14:46 UTC
